// Generated by gencpp from file action_mul/SquareNumFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_MUL_MESSAGE_SQUARENUMFEEDBACK_H
#define ACTION_MUL_MESSAGE_SQUARENUMFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_mul
{
template <class ContainerAllocator>
struct SquareNumFeedback_
{
  typedef SquareNumFeedback_<ContainerAllocator> Type;

  SquareNumFeedback_()
    : percentage(0.0)  {
    }
  SquareNumFeedback_(const ContainerAllocator& _alloc)
    : percentage(0.0)  {
  (void)_alloc;
    }



   typedef double _percentage_type;
  _percentage_type percentage;





  typedef boost::shared_ptr< ::action_mul::SquareNumFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_mul::SquareNumFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SquareNumFeedback_

typedef ::action_mul::SquareNumFeedback_<std::allocator<void> > SquareNumFeedback;

typedef boost::shared_ptr< ::action_mul::SquareNumFeedback > SquareNumFeedbackPtr;
typedef boost::shared_ptr< ::action_mul::SquareNumFeedback const> SquareNumFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_mul::SquareNumFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_mul::SquareNumFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_mul::SquareNumFeedback_<ContainerAllocator1> & lhs, const ::action_mul::SquareNumFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percentage == rhs.percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_mul::SquareNumFeedback_<ContainerAllocator1> & lhs, const ::action_mul::SquareNumFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_mul

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::action_mul::SquareNumFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_mul::SquareNumFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_mul::SquareNumFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_mul::SquareNumFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_mul::SquareNumFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_mul::SquareNumFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_mul::SquareNumFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46302a97c06fe5a4416c427fe6ee8804";
  }

  static const char* value(const ::action_mul::SquareNumFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46302a97c06fe5a4ULL;
  static const uint64_t static_value2 = 0x416c427fe6ee8804ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_mul::SquareNumFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_mul/SquareNumFeedback";
  }

  static const char* value(const ::action_mul::SquareNumFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_mul::SquareNumFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64 percentage\n"
"\n"
;
  }

  static const char* value(const ::action_mul::SquareNumFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_mul::SquareNumFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SquareNumFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_mul::SquareNumFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_mul::SquareNumFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<double>::stream(s, indent + "  ", v.percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_MUL_MESSAGE_SQUARENUMFEEDBACK_H
