// Generated by gencpp from file msg_serv/MulTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef MSG_SERV_MESSAGE_MULTWOINTSRESPONSE_H
#define MSG_SERV_MESSAGE_MULTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_serv
{
template <class ContainerAllocator>
struct MulTwoIntsResponse_
{
  typedef MulTwoIntsResponse_<ContainerAllocator> Type;

  MulTwoIntsResponse_()
    : mul(0)  {
    }
  MulTwoIntsResponse_(const ContainerAllocator& _alloc)
    : mul(0)  {
  (void)_alloc;
    }



   typedef int64_t _mul_type;
  _mul_type mul;





  typedef boost::shared_ptr< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MulTwoIntsResponse_

typedef ::msg_serv::MulTwoIntsResponse_<std::allocator<void> > MulTwoIntsResponse;

typedef boost::shared_ptr< ::msg_serv::MulTwoIntsResponse > MulTwoIntsResponsePtr;
typedef boost::shared_ptr< ::msg_serv::MulTwoIntsResponse const> MulTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_serv::MulTwoIntsResponse_<ContainerAllocator1> & lhs, const ::msg_serv::MulTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.mul == rhs.mul;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_serv::MulTwoIntsResponse_<ContainerAllocator1> & lhs, const ::msg_serv::MulTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_serv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f17363cd17c14ac0fae7fd5c952ba3d";
  }

  static const char* value(const ::msg_serv::MulTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f17363cd17c14acULL;
  static const uint64_t static_value2 = 0x0fae7fd5c952ba3dULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_serv/MulTwoIntsResponse";
  }

  static const char* value(const ::msg_serv::MulTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 mul\n"
"\n"
;
  }

  static const char* value(const ::msg_serv::MulTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mul);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MulTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_serv::MulTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_serv::MulTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "mul: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mul);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_SERV_MESSAGE_MULTWOINTSRESPONSE_H
