// Generated by gencpp from file msg_serv/MulTwoIntsRequest.msg
// DO NOT EDIT!


#ifndef MSG_SERV_MESSAGE_MULTWOINTSREQUEST_H
#define MSG_SERV_MESSAGE_MULTWOINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_serv
{
template <class ContainerAllocator>
struct MulTwoIntsRequest_
{
  typedef MulTwoIntsRequest_<ContainerAllocator> Type;

  MulTwoIntsRequest_()
    : a(0)
    , b(0)  {
    }
  MulTwoIntsRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MulTwoIntsRequest_

typedef ::msg_serv::MulTwoIntsRequest_<std::allocator<void> > MulTwoIntsRequest;

typedef boost::shared_ptr< ::msg_serv::MulTwoIntsRequest > MulTwoIntsRequestPtr;
typedef boost::shared_ptr< ::msg_serv::MulTwoIntsRequest const> MulTwoIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_serv::MulTwoIntsRequest_<ContainerAllocator1> & lhs, const ::msg_serv::MulTwoIntsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_serv::MulTwoIntsRequest_<ContainerAllocator1> & lhs, const ::msg_serv::MulTwoIntsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_serv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::msg_serv::MulTwoIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_serv/MulTwoIntsRequest";
  }

  static const char* value(const ::msg_serv::MulTwoIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::msg_serv::MulTwoIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MulTwoIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_serv::MulTwoIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_serv::MulTwoIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_SERV_MESSAGE_MULTWOINTSREQUEST_H
