// Generated by gencpp from file msg_serv/MulTwoInts.msg
// DO NOT EDIT!


#ifndef MSG_SERV_MESSAGE_MULTWOINTS_H
#define MSG_SERV_MESSAGE_MULTWOINTS_H

#include <ros/service_traits.h>


#include <msg_serv/MulTwoIntsRequest.h>
#include <msg_serv/MulTwoIntsResponse.h>


namespace msg_serv
{

struct MulTwoInts
{

typedef MulTwoIntsRequest Request;
typedef MulTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MulTwoInts
} // namespace msg_serv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msg_serv::MulTwoInts > {
  static const char* value()
  {
    return "775025c798d6c657309501de3b5e15ed";
  }

  static const char* value(const ::msg_serv::MulTwoInts&) { return value(); }
};

template<>
struct DataType< ::msg_serv::MulTwoInts > {
  static const char* value()
  {
    return "msg_serv/MulTwoInts";
  }

  static const char* value(const ::msg_serv::MulTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::msg_serv::MulTwoIntsRequest> should match
// service_traits::MD5Sum< ::msg_serv::MulTwoInts >
template<>
struct MD5Sum< ::msg_serv::MulTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msg_serv::MulTwoInts >::value();
  }
  static const char* value(const ::msg_serv::MulTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msg_serv::MulTwoIntsRequest> should match
// service_traits::DataType< ::msg_serv::MulTwoInts >
template<>
struct DataType< ::msg_serv::MulTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::msg_serv::MulTwoInts >::value();
  }
  static const char* value(const ::msg_serv::MulTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msg_serv::MulTwoIntsResponse> should match
// service_traits::MD5Sum< ::msg_serv::MulTwoInts >
template<>
struct MD5Sum< ::msg_serv::MulTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msg_serv::MulTwoInts >::value();
  }
  static const char* value(const ::msg_serv::MulTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msg_serv::MulTwoIntsResponse> should match
// service_traits::DataType< ::msg_serv::MulTwoInts >
template<>
struct DataType< ::msg_serv::MulTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::msg_serv::MulTwoInts >::value();
  }
  static const char* value(const ::msg_serv::MulTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSG_SERV_MESSAGE_MULTWOINTS_H
