(cl:defpackage action_mul-msg
  (:use )
  (:export
   "<SQUARENUMACTION>"
   "SQUARENUMACTION"
   "<SQUARENUMACTIONFEEDBACK>"
   "SQUARENUMACTIONFEEDBACK"
   "<SQUARENUMACTIONGOAL>"
   "SQUARENUMACTIONGOAL"
   "<SQUARENUMACTIONRESULT>"
   "SQUARENUMACTIONRESULT"
   "<SQUARENUMFEEDBACK>"
   "SQUARENUMFEEDBACK"
   "<SQUARENUMGOAL>"
   "SQUARENUMGOAL"
   "<SQUARENUMRESULT>"
   "SQUARENUMRESULT"
  ))

